site_name: "MoSAIC"
site_description: "Correlation-based feature selection of MD simulations."
site_url: "https://moldyn.github.io/MoSAIC"
repo_url: "https://github.com/moldyn/MoSAIC"
edit_uri: "blob/main/docs/"
repo_name: "moldyn/MoSAIC"
site_dir: "site"
copyright: Copyright &copy; 2019-2023 Daniel Nagel and Georg Diez
watch: [src/mosaic]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - License: license.md
- Tutorials:
  - MoSAIC workflow: tutorial/t4l_tutorial_github.ipynb
  - Crossvalidation: tutorial/cv.md

- FAQ: faq.md
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Maintenance: maintenance.md
- MolDyn Freiburg: https://moldyn.uni-freiburg.de/

theme:
  name: material
  favicon: icon.png
  logo_slate_mode: icon.png
  logo_default_mode: icon.png
  custom_dir: docs/overrides
  features:
  - content.code.annotate
  - navigation.tabs
  - navigation.top
  font:
    text: Source Sans Pro
    headline: Playfair Display
    code: Source Code Pro
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - mkdocs-click
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
- section-index
- search
- privacy
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- mkdocs-jupyter:
    include: ["*.ipynb"]
    execute: false
    allow_errors: false
    ignore_h1_titles: true
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        import:
        - https://numpy.org/doc/stable/objects.inv
        options:
          members_order: "source"
          docstring_style: "numpy"
          docstring_section_style: "list"
          merge_init_into_class: true
          filters: ["!^_"]

extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
  - icon: fontawesome/solid/globe
    link: https://www.moldyn.uni-freiburg.de
  - icon: fontawesome/brands/github
    link: https://github.com/moldyn
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/MolDynFR
